/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import classes.AutoCompletion;
import classes.daily_class;
import classes.moshtarayat_class;
import entities.DAILY;
import entities.MOSHTARAYAT;
import java.awt.event.KeyEvent;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nowar
 */
public class daily extends javax.swing.JFrame {

    /**
     * Creates new form daily
     */
    public daily() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public static java.sql.Date convertFromJAVADateToSQLDate(
            java.util.Date javaDate) {
        java.sql.Date sqlDate = null;
        if (javaDate != null) {
            sqlDate = new Date(javaDate.getTime());
        }
        return sqlDate;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        old = new javax.swing.JComboBox<>();
        ob_amount = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jprice = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jtotalprice = new javax.swing.JTextField();
        unit = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arabic Typesetting", 1, 48)); // NOI18N
        jLabel1.setText("إدخال مبيع يومي");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("اسم المادة :");

        old.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        old.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));
        old.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                oldItemStateChanged(evt);
            }
        });

        ob_amount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ob_amount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ob_amountKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ob_amountKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("الكمية :");

        jprice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jprice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jpriceKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jpriceKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("السعر :");

        jDateChooser1.setDateFormatString("yyyy-MM-dd");
        jDateChooser1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("التاريخ :");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("حفظ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2.setText("عودة");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("الإجمالي :");

        jtotalprice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtotalprice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtotalpriceKeyTyped(evt);
            }
        });

        unit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        unit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "قطعة", "دزينة" }));
        unit.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                unitItemStateChanged(evt);
            }
        });
        unit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unitActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("الوحدة :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtotalprice)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addComponent(old, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jprice)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ob_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(unit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel10)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(old, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ob_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jprice, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtotalprice, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(333, 333, 333)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ob_amountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ob_amountKeyReleased
        try {
            Double x = Double.parseDouble(ob_amount.getText());
            if (!ob_amount.getText().equals("")) {
                int y = Integer.parseInt(jprice.getText());
                Double z = x * y;
                jtotalprice.setText(String.valueOf(z));
            } else {
                jtotalprice.setText(String.valueOf(0));
                ob_amount.setText(String.valueOf(0));
            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_ob_amountKeyReleased

    private void ob_amountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ob_amountKeyTyped

    }//GEN-LAST:event_ob_amountKeyTyped

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        int count = 0;
        int compare = 0;
        Object obj;
        String name = "";
        boolean added;
        java.util.Date date = new java.util.Date();
        jDateChooser1.setDate(date);
        MOSHTARAYAT m = new MOSHTARAYAT();
        moshtarayat_class mc = new moshtarayat_class();
        ArrayList<String> ar = mc.getobjectsname();
        for (int j = 0; j < ar.size(); j++) {
            name = ar.get(j);
            count = old.getItemCount();
            added = false;
            for (int i = 1; i < count; i++) {
                obj = old.getItemAt(i);
                compare = name.compareToIgnoreCase(obj.toString());
                if (compare <= 0) {
                    old.insertItemAt(name, i);
                    added = true;
                    break;
                }
            }
            if (!added) {
                old.addItem(name);
            }
        }
        AutoCompletion.enable(old);
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String name = old.getSelectedItem().toString();
       
        
        String un = unit.getSelectedItem().toString();
       
        Date da = convertFromJAVADateToSQLDate(jDateChooser1.getDate());

        daily_class daily = new daily_class();
        DAILY d = new DAILY();
        if (!old.getSelectedItem().toString().equalsIgnoreCase("-") && !ob_amount.getText().equalsIgnoreCase("") && !jprice.getText().equalsIgnoreCase("")) {
            try {
                 Double amount = Double.parseDouble(ob_amount.getText());
                 Double total = Double.parseDouble(jtotalprice.getText());
                 int price = Integer.parseInt(jprice.getText());
                d.setObname(name);
                d.setObamount(amount);
                d.setObprice(price);
                d.setTotalprice(total);
                d.setObdate(da);
                d.setObunit(un);
                daily.addDaily(d);
                old.setSelectedItem("-");
                ob_amount.setText("");
                jprice.setText("");
                jtotalprice.setText("");

                ((DefaultTableModel) jTable1.getModel()).setNumRows(0);
                DefaultTableModel tbd = new DefaultTableModel();
                ArrayList<DAILY> ar = daily.showdaily();
                Object[] tablecolumnNames = new Object[7];
                tablecolumnNames[0] = "التاريخ";
                tablecolumnNames[1] = "الإجمالي";
                tablecolumnNames[2] = "السعر";
                tablecolumnNames[3] = "الكمية";
                tablecolumnNames[4] = "الوحدة";
                tablecolumnNames[5] = "اسم القطعة";
                tablecolumnNames[6] = "الرقم";

                tbd.setColumnIdentifiers(tablecolumnNames);

                this.jTable1.setModel(tbd);
                Object[] RowItem = new Object[7];

                for (int i = 0; i < ar.size(); i++) {

                    RowItem[0] = ar.get(i).getObdate();

                    RowItem[1] = ar.get(i).getTotalprice();
                    RowItem[2] = ar.get(i).getObprice();
                    RowItem[3] = ar.get(i).getObamount();
                    RowItem[4] = ar.get(i).getObunit();
                    RowItem[5] = ar.get(i).getObname();
                    RowItem[6] = ar.get(i).getId();
                    tbd.addRow(RowItem);
                }

            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "الرجاء ملئ كافة الحقول");
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jpriceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpriceKeyReleased
        try {
            Double x = Double.parseDouble(ob_amount.getText());
            if (!jprice.getText().equals("") && !ob_amount.getText().equals("")) {
                int y = Integer.parseInt(jprice.getText());
                Double z = x * y;
                jtotalprice.setText(String.valueOf(z));
            } else {
                jtotalprice.setText(String.valueOf(0));

            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_jpriceKeyReleased

    private void jpriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpriceKeyTyped
        char vchar = evt.getKeyChar();
        if (!(Character.isDigit(vchar)) || (vchar == KeyEvent.VK_BACK_SPACE) || (vchar == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_jpriceKeyTyped

    private void jtotalpriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtotalpriceKeyTyped
        char vchar = evt.getKeyChar();
        if (!(Character.isDigit(vchar)) || (vchar == KeyEvent.VK_BACK_SPACE) || (vchar == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_jtotalpriceKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        First_view p = First_view.instance();
        p.pack();
        p.setLocationRelativeTo(null);
        p.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void unitItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_unitItemStateChanged
    moshtarayat_class mo = new moshtarayat_class();
        String un = unit.getSelectedItem().toString();
        ArrayList<Integer> ar = mo.getobjectinfo(old.getSelectedItem().toString());

        if (un.equalsIgnoreCase("قطعة")) {
            jprice.setText(String.valueOf(ar.get(4)));

        } else {
            jprice.setText(String.valueOf(ar.get(5)));

        }
    }//GEN-LAST:event_unitItemStateChanged

    private void unitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unitActionPerformed

    private void oldItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_oldItemStateChanged
        moshtarayat_class mo = new moshtarayat_class();
        String un = unit.getSelectedItem().toString();
        ArrayList<Integer> ar = mo.getobjectinfo(old.getSelectedItem().toString());

        if (un.equalsIgnoreCase("قطعة")) {
            jprice.setText(String.valueOf(ar.get(4)));

        } else {
            jprice.setText(String.valueOf(ar.get(5)));

        }
    }//GEN-LAST:event_oldItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(daily.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(daily.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(daily.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(daily.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new daily().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jprice;
    private javax.swing.JTextField jtotalprice;
    private javax.swing.JTextField ob_amount;
    private javax.swing.JComboBox<String> old;
    private javax.swing.JComboBox<String> unit;
    // End of variables declaration//GEN-END:variables
}
