/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import classes.jard_class;
import entities.DAILY;
import entities.MABE3AT;
import entities.MOSHTARAYAT;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nowar
 */
public class jardshahre extends javax.swing.JFrame {

    private double counttablecolumns = 0;
    private double sumvalues = 0;

    /**
     * Creates new form jardshahre
     */
    public jardshahre() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        result = new javax.swing.JButton();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        radio_mosh = new javax.swing.JRadioButton();
        radio_mab = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        cocount = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        sumval = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        radio_daily = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arabic Typesetting", 1, 36)); // NOI18N
        jLabel1.setText("جرد يوم \\ شهر \\ سنة");

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setRowHeight(23);
        jScrollPane1.setViewportView(jTable1);

        result.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        result.setText("النتيجة ");
        result.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultActionPerformed(evt);
            }
        });

        jDateChooser2.setDateFormatString("yyyy-MM-dd");

        jDateChooser1.setDateFormatString("yyyy-MM-dd");

        buttonGroup1.add(radio_mosh);
        radio_mosh.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        radio_mosh.setText("مشتريات");
        radio_mosh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_moshActionPerformed(evt);
            }
        });

        buttonGroup1.add(radio_mab);
        radio_mab.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        radio_mab.setText("مبيع جملة");

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cocount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cocount.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        cocount.setEnabled(false);
        jPanel4.add(cocount, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 130, 30));

        jLabel12.setFont(new java.awt.Font("AdvertisingExtraBold", 0, 18)); // NOI18N
        jLabel12.setText("عدد الصفوف :");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, -1, -1));

        jLabel17.setFont(new java.awt.Font("AdvertisingExtraBold", 0, 24)); // NOI18N
        jLabel17.setText("الاحصائيات");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        sumval.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sumval.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        sumval.setEnabled(false);
        jPanel4.add(sumval, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 130, 30));

        jLabel13.setFont(new java.awt.Font("AdvertisingExtraBold", 0, 18)); // NOI18N
        jLabel13.setText("المبلغ الإجمالي :");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("إلى تاريخ :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("من تاريخ :");

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton3.setText("عودة");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(radio_daily);
        radio_daily.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        radio_daily.setText("مبيع يومي");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radio_mosh)
                            .addComponent(radio_mab)
                            .addComponent(radio_daily))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jDateChooser2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(result, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(17, 17, 17))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(304, 304, 304)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(result))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)))
                        .addGap(23, 23, 23)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(radio_mab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radio_mosh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radio_daily)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultActionPerformed
        counttablecolumns = 0;
        sumvalues = 0;
        String d11 = new SimpleDateFormat("yyyy-MM-dd").format(jDateChooser1.getDate());
        String d22 = new SimpleDateFormat("yyyy-MM-dd").format(jDateChooser2.getDate());
        System.out.println(d11);
        String full1 = "where ob_date between #" + d11 + "# and  #" + d22 + "# ";
        String full12 = "where ma_date between #" + d11 + "# and  #" + d22 + "# ";
        String full13 = "where obdate between #" + d11 + "# and  #" + d22 + "# ";
        jard_class tc = new jard_class();
        if (radio_mosh.isSelected()) {
            ArrayList<MOSHTARAYAT> ar = tc.rsultmoshtarayat(full1);

            DefaultTableModel tbd = new DefaultTableModel();
            Object[] tablecolumnNames = new Object[7];
            tablecolumnNames[0] = "التاريخ";
            tablecolumnNames[1] = "الإجمالي";
            tablecolumnNames[2] = "سعر الوحدة";
            tablecolumnNames[3] = "الوحدة";
            tablecolumnNames[4] = "الكمية";
            tablecolumnNames[5] = "اسم القطعة";
            tablecolumnNames[6] = "الرقم";

            tbd.setColumnIdentifiers(tablecolumnNames);

            this.jTable1.setModel(tbd);
            Object[] RowItem = new Object[7];

            for (int i = 0; i < ar.size(); i++) {

                RowItem[0] = ar.get(i).getOb_date();
                RowItem[1] = ar.get(i).getTotal_price();
                sumvalues = sumvalues + ar.get(i).getTotal_price();
                RowItem[2] = ar.get(i).getUnit_price();
                RowItem[3] = ar.get(i).getUnit();
                RowItem[4] = ar.get(i).getAmount();
                RowItem[5] = ar.get(i).getName();
                RowItem[6] = ar.get(i).getId();
                tbd.addRow(RowItem);
                counttablecolumns++;
            }
            cocount.setText(String.valueOf(counttablecolumns));
            sumval.setText(String.valueOf(sumvalues));

        }
        if (radio_mab.isSelected()) {
            ArrayList<MABE3AT> ar = tc.rsultmabe3at(full12);

            DefaultTableModel tbd = new DefaultTableModel();

            Object[] tablecolumnNames = new Object[8];
            tablecolumnNames[0] = "التاريخ";
            tablecolumnNames[1] = "سعر المستهلك";
            tablecolumnNames[2] = "الإجمالي";
            tablecolumnNames[3] = "سعر الوحدة";
            tablecolumnNames[4] = "الوحدة";
            tablecolumnNames[5] = "الكمية";
            tablecolumnNames[6] = "اسم القطعة";
            tablecolumnNames[7] = "الرقم";

            tbd.setColumnIdentifiers(tablecolumnNames);

            this.jTable1.setModel(tbd);
            Object[] RowItem = new Object[8];

            for (int i = 0; i < ar.size(); i++) {

                RowItem[0] = ar.get(i).getMa_date();
                RowItem[1] = ar.get(i).getCons_price();
                RowItem[2] = ar.get(i).getTotalprice();
                sumvalues = sumvalues + ar.get(i).getTotalprice();
                RowItem[3] = ar.get(i).getPrice();
                RowItem[4] = ar.get(i).getUnit();
                RowItem[5] = ar.get(i).getAmount();
                RowItem[6] = ar.get(i).getName();
                RowItem[7] = ar.get(i).getId();
                tbd.addRow(RowItem);
                counttablecolumns++;
            }
            cocount.setText(String.valueOf(counttablecolumns));
            sumval.setText(String.valueOf(sumvalues));

        }
        if (radio_daily.isSelected()) {
            ArrayList<DAILY> ar = tc.rsultdaily(full13);
            DefaultTableModel tbd = new DefaultTableModel();
            Object[] tablecolumnNames = new Object[7];
            tablecolumnNames[0] = "التاريخ";
            tablecolumnNames[1] = "الإجمالي";
            tablecolumnNames[2] = "السعر";
            tablecolumnNames[3] = "الكمية";
            tablecolumnNames[4] = "الوحدة";
            tablecolumnNames[5] = "اسم القطعة";
            tablecolumnNames[6] = "الرقم";

            tbd.setColumnIdentifiers(tablecolumnNames);

            this.jTable1.setModel(tbd);
            Object[] RowItem = new Object[7];

            for (int i = 0; i < ar.size(); i++) {

                RowItem[0] = ar.get(i).getObdate();
                sumvalues = sumvalues + ar.get(i).getTotalprice();
                RowItem[1] = ar.get(i).getTotalprice();
                RowItem[2] = ar.get(i).getObprice();
                RowItem[3] = ar.get(i).getObamount();
                RowItem[4] = ar.get(i).getObunit();
                RowItem[5] = ar.get(i).getObname();
                RowItem[6] = ar.get(i).getId();
                tbd.addRow(RowItem);
                counttablecolumns++;
            }
            cocount.setText(String.valueOf(counttablecolumns));
            sumval.setText(String.valueOf(sumvalues));
        }

        // System.out.println(d11);

    }//GEN-LAST:event_resultActionPerformed

    private void radio_moshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_moshActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_moshActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setVisible(false);
        First_view p = First_view.instance();
        p.pack();
        p.setLocationRelativeTo(null);
        p.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        Date date = new Date();
        DateFormat dateformat = new SimpleDateFormat("yyyy-MM-dd");
        String s = dateformat.format(date);
        Calendar cal = Calendar.getInstance();
        try {
            cal.setTime(dateformat.parse(s));
        } catch (ParseException ex) {
            Logger.getLogger(jardshahre.class.getName()).log(Level.SEVERE, null, ex);
        }
        cal.add(Calendar.DATE, 1);
        jDateChooser2.setDate(cal.getTime());

        String dateValue = "2018-08-07";  // must be in (yyyy- mm- dd ) format
        Date date2;

        try {
            date2 = new SimpleDateFormat("yyyy-MM-dd").parse(dateValue);
            jDateChooser1.setDate(date2);
        } catch (ParseException ex) {
            //   Logger.getLogger(queries.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jardshahre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jardshahre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jardshahre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jardshahre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jardshahre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cocount;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton radio_daily;
    private javax.swing.JRadioButton radio_mab;
    private javax.swing.JRadioButton radio_mosh;
    private javax.swing.JButton result;
    private javax.swing.JTextField sumval;
    // End of variables declaration//GEN-END:variables
}
