/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import classes.AutoCompletion;
import classes.mabe3at_class;
import classes.moshtarayat_class;
import entities.MABE3AT;
import entities.MOSHTARAYAT;
import java.awt.event.KeyEvent;
import java.awt.print.PrinterException;
import java.sql.Date;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import static views.moshtarayat.convertFromJAVADateToSQLDate;

/**
 *
 * @author Nowar
 */
public class MABE3AT_view extends javax.swing.JFrame {

    Double sum = 0.0;
    boolean state = false;
    String zbon_name="";

    /**
     * Creates new form MABE3AT
     */
    public MABE3AT_view() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public void initializetextarea(){
        mabe3at_class mo = new mabe3at_class();
        int bid = Integer.parseInt(jTextField1.getText());
        ArrayList<MABE3AT> ar = mo.showmabe3at(zbon_name, bid);
        String data="";
        for (int i = 0; i < ar.size(); i++) {
         data=""+ar.get(i).getCons_price()+"    "+ar.get(i).getTotalprice()+"   "+ar.get(i).getPrice()+"    "+ar.get(i).getUnit()+"    "+ar.get(i).getAmount()+"    "+ar.get(i).getName()+"    "+ar.get(i).getId()+"";
         jTextArea1.append(data);
        }
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        zbonname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        consnum = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        unit = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jname = new javax.swing.JComboBox<>();
        ob_amount = new javax.swing.JTextField();
        u_price = new javax.swing.JTextField();
        to_price = new javax.swing.JTextField();
        c_price = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 874, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arabic Typesetting", 1, 36)); // NOI18N
        jLabel1.setText("فاتورة");

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setRowHeight(23);
        jScrollPane1.setViewportView(jTable1);

        zbonname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                zbonnameKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("اسم الزبون :");

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("الرقم :");

        consnum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                consnumKeyTyped(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("اسم المادة :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("الكمية :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("الوحدة :");

        unit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        unit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "قطعة", "دزينة" }));
        unit.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                unitItemStateChanged(evt);
            }
        });
        unit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unitActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("السعر الإفرادي :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("إجمالي السعر :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("سعر المستهلك :");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("التاريخ :");

        jDateChooser1.setDateFormatString("yyyy-MM-dd");
        jDateChooser1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));
        jname.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jnameItemStateChanged(evt);
            }
        });

        ob_amount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ob_amount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ob_amountKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ob_amountKeyTyped(evt);
            }
        });

        u_price.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        u_price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                u_priceKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                u_priceKeyTyped(evt);
            }
        });

        to_price.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        to_price.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        to_price.setEnabled(false);
        to_price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                to_priceKeyTyped(evt);
            }
        });

        c_price.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        c_price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                c_priceKeyTyped(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("حفظ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("طباعة فاتورة");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("عودة");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("الباقي :");

        jTextField2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField2.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jname, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(u_price, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c_price, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(to_price, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(unit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ob_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel8)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(1, 1, 1)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel6)
                                                .addComponent(jLabel4))))
                                    .addGap(8, 8, 8))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addContainerGap()))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel5))
                                .addContainerGap())))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(172, 172, 172))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jname, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ob_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(u_price, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(to_price, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(unit, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel12)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(c_price, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("رقم الفاتورة :");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton4.setText("+");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(consnum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(zbonname, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(161, 383, Short.MAX_VALUE)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(511, 511, 511))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(consnum, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(zbonname, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ob_amountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ob_amountKeyReleased
        try {
            Double x = Double.parseDouble(ob_amount.getText());
            if (!ob_amount.getText().equals("")) {
                int y = Integer.parseInt(u_price.getText());
                Double z = x * y;
                to_price.setText(String.valueOf(z));
            } else {
                to_price.setText(String.valueOf(0));
                ob_amount.setText(String.valueOf(0));
            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_ob_amountKeyReleased

    private void ob_amountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ob_amountKeyTyped

    }//GEN-LAST:event_ob_amountKeyTyped

    private void u_priceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_u_priceKeyReleased
        try {
            Double x = Double.parseDouble(ob_amount.getText());
            if (!u_price.getText().equals("") && !ob_amount.getText().equals("")) {
                int y = Integer.parseInt(u_price.getText());
                Double z = x * y;
                to_price.setText(String.valueOf(z));
            } else {
                to_price.setText(String.valueOf(0));

            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_u_priceKeyReleased

    private void u_priceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_u_priceKeyTyped
        char vchar = evt.getKeyChar();
        if (!(Character.isDigit(vchar)) || (vchar == KeyEvent.VK_BACK_SPACE) || (vchar == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_u_priceKeyTyped

    private void to_priceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_to_priceKeyTyped
        char vchar = evt.getKeyChar();
        if (!(Character.isDigit(vchar)) || (vchar == KeyEvent.VK_BACK_SPACE) || (vchar == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_to_priceKeyTyped

    private void c_priceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_c_priceKeyTyped
        char vchar = evt.getKeyChar();
        if (!(Character.isDigit(vchar)) || (vchar == KeyEvent.VK_BACK_SPACE) || (vchar == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_c_priceKeyTyped

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        int count = 0;
        int compare = 0;
        Object obj;
        String name = "";
        boolean added;
        java.util.Date date = new java.util.Date();
        jDateChooser1.setDate(date);
        MABE3AT m = new MABE3AT();
        mabe3at_class mc = new mabe3at_class();
        ArrayList<String> ar = mc.getzbonsname();
        MOSHTARAYAT m1 = new MOSHTARAYAT();
        moshtarayat_class mc1 = new moshtarayat_class();
        ArrayList<String> ar1 = mc1.getobjectsname();
        for (int j = 0; j < ar.size(); j++) {
            name = ar.get(j);
            count = jComboBox1.getItemCount();
            added = false;
            for (int i = 1; i < count; i++) {
                obj = jComboBox1.getItemAt(i);
                compare = name.compareToIgnoreCase(obj.toString());
                if (compare <= 0) {
                    jComboBox1.insertItemAt(name, i);
                    added = true;
                    break;
                }
            }
            if (!added) {
                jComboBox1.addItem(name);
            }
        }
        AutoCompletion.enable(jComboBox1);

        for (int j = 0; j < ar1.size(); j++) {
            name = ar1.get(j);
            count = jname.getItemCount();
            added = false;
            for (int i = 1; i < count; i++) {
                obj = jname.getItemAt(i);
                compare = name.compareToIgnoreCase(obj.toString());
                if (compare <= 0) {
                    jname.insertItemAt(name, i);
                    added = true;
                    break;
                }
            }
            if (!added) {
                jname.addItem(name);
            }
        }
        AutoCompletion.enable(jname);
        int billid = mc.maxbillid() + 1;
        jTextField1.setText(String.valueOf(billid));
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int count = 0;
        int compare = 0;
        Object obj;

        boolean added;
        MABE3AT en = new MABE3AT();
        mabe3at_class mo = new mabe3at_class();
         zbon_name = "";
        int zid = 0;
        if ((!zbonname.getText().equals("") || !jComboBox1.getSelectedItem().toString().equalsIgnoreCase("-")) && !consnum.getText().equals("")) {
            if (state) {
                zbon_name = jComboBox1.getSelectedItem().toString();

            } else {
                zbon_name = zbonname.getText();
            }
            zid = Integer.parseInt(consnum.getText());
            Date date = convertFromJAVADateToSQLDate(jDateChooser1.getDate());
            if (!jname.getSelectedItem().toString().equalsIgnoreCase("-") && !ob_amount.getText().equals("") && !u_price.getText().equals("")
                    && !to_price.getText().equals("") && !c_price.getText().equals("")) {

                String name = jname.getSelectedItem().toString();

                Double amount = Double.parseDouble(ob_amount.getText());
                String Sunit = unit.getSelectedItem().toString();
                int unit_price = Integer.parseInt(u_price.getText());
                Double total_price = Double.parseDouble(to_price.getText());
                sum = sum + total_price;

                int consumer_price = Integer.parseInt(c_price.getText());
                en.setName(name);
                en.setAmount(amount);
                en.setUnit(Sunit);
                en.setPrice(unit_price);
                en.setTotalprice(total_price);
                en.setCons_price(consumer_price);
                en.setConid(zid);
                en.setMa_date(date);
                try {
                    mo.addmabe3at(en);
                    int x = mo.maxnumber();

                    int bid = Integer.parseInt(jTextField1.getText());
                    mo.addzbon(zid, zbon_name, x, bid);

                    jname.setSelectedItem("-");
                    ob_amount.setText("");
                    u_price.setText("");
                    to_price.setText("");
                    c_price.setText("");
                    jTextField2.setText("");

                    ((DefaultTableModel) jTable1.getModel()).setNumRows(0);
                    DefaultTableModel tbd = new DefaultTableModel();
                    ArrayList<MABE3AT> ar = mo.showmabe3at(zbon_name, bid);
                    Object[] tablecolumnNames = new Object[8];
                    tablecolumnNames[0] = "التاريخ";
                    tablecolumnNames[1] = "سعر المستهلك";
                    tablecolumnNames[2] = "الإجمالي";
                    tablecolumnNames[3] = "سعر الوحدة";
                    tablecolumnNames[4] = "الوحدة";
                    tablecolumnNames[5] = "الكمية";
                    tablecolumnNames[6] = "اسم القطعة";
                    tablecolumnNames[7] = "الرقم";

                    tbd.setColumnIdentifiers(tablecolumnNames);

                    this.jTable1.setModel(tbd);
                    Object[] RowItem = new Object[8];

                    for (int i = 0; i < ar.size(); i++) {

                        RowItem[0] = ar.get(i).getMa_date();
                        RowItem[1] = ar.get(i).getCons_price();
                        RowItem[2] = ar.get(i).getTotalprice();

                        RowItem[3] = ar.get(i).getPrice();
                        RowItem[4] = ar.get(i).getUnit();
                        RowItem[5] = ar.get(i).getAmount();
                        RowItem[6] = ar.get(i).getName();
                        RowItem[7] = ar.get(i).getId();
                        tbd.addRow(RowItem);
                    }
                     TableColumn t= jTable1.getColumnModel().getColumn(6);
                     TableColumn t1= jTable1.getColumnModel().getColumn(7);
                      TableColumn t2= jTable1.getColumnModel().getColumn(5);
                     t.setPreferredWidth(250);
                     t1.setPreferredWidth(30);
                     t2.setPreferredWidth(55);
                     

                } catch (SQLException ex) {
                    Logger.getLogger(moshtarayat.class.getName()).log(Level.SEVERE, null, ex);
                }

            } else {
                JOptionPane.showMessageDialog(null, "الرجاء ملئ جميع الحقول");
            }

        } else {
            JOptionPane.showMessageDialog(null, "الرجاء إدخال اسم الزبون مع الرقم");

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void zbonnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_zbonnameKeyTyped
        state = false;
        jComboBox1.setSelectedItem("-");
        mabe3at_class m = new mabe3at_class();
        int x = m.maxzid() + 1;
        consnum.setText(String.valueOf(x));

    }//GEN-LAST:event_zbonnameKeyTyped

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        state = true;
        zbonname.setText("");
        mabe3at_class ma = new mabe3at_class();
        int n = ma.ConsumerNumber(jComboBox1.getSelectedItem().toString());
        consnum.setText(String.valueOf(n));
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void consnumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_consnumKeyTyped
        char vchar = evt.getKeyChar();
        if (!(Character.isDigit(vchar)) || (vchar == KeyEvent.VK_BACK_SPACE) || (vchar == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_consnumKeyTyped

    private void jnameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jnameItemStateChanged
        moshtarayat_class moc = new moshtarayat_class();
        String name = jname.getSelectedItem().toString();
        String un = unit.getSelectedItem().toString();
        Double x = moc.getx(name, un);
        Double y = moc.gety(name, un);
        Double z = moc.getz(name, un);
        Double n = x - y - z;
        System.out.println("x is " + x);
        System.out.println("y is " + y);
        System.out.println("z is " + z);
        System.out.println("n is " + n);
        jTextField2.setText(String.valueOf(n));
        ArrayList<Integer> ar = moc.getobjectinfo(name);
        if (un.equalsIgnoreCase("قطعة")) {
            u_price.setText(String.valueOf(ar.get(3)));

            c_price.setText(String.valueOf(ar.get(4)));
        } else {
            u_price.setText(String.valueOf(ar.get(6)));

            c_price.setText(String.valueOf(ar.get(5)));
        }

    }//GEN-LAST:event_jnameItemStateChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setVisible(false);
        First_view p = First_view.instance();
        p.pack();
        p.setLocationRelativeTo(null);
        p.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int x = Integer.parseInt(jTextField1.getText()) + 1;
        jTextField1.setText(String.valueOf(x));
    }//GEN-LAST:event_jButton4ActionPerformed

    private void unitItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_unitItemStateChanged
        moshtarayat_class moc = new moshtarayat_class();
        String name = jname.getSelectedItem().toString();
        String un = unit.getSelectedItem().toString();

        Double x = moc.getx(name, un);
        Double y = moc.gety(name, un);
        Double z = moc.getz(name, un);
        Double n = x - y - z;
        System.out.println("x is " + x);
        System.out.println("y is " + y);
        System.out.println("z is " + z);
        System.out.println("n is " + n);
        jTextField2.setText(String.valueOf(n));
        ArrayList<Integer> ar = moc.getobjectinfo(name);
        if (un.equalsIgnoreCase("قطعة")) {
            u_price.setText(String.valueOf(ar.get(3)));

            c_price.setText(String.valueOf(ar.get(4)));
        } else {
            u_price.setText(String.valueOf(ar.get(6)));

            c_price.setText(String.valueOf(ar.get(5)));
        }
    }//GEN-LAST:event_unitItemStateChanged

    private void unitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unitActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      try{
          jPanel2.setVisible(true);
          initializetextarea();
          boolean complete=jTextArea1.print();
          if(complete){
              JOptionPane.showMessageDialog(null, "Done Printing", "Information", JOptionPane.INFORMATION_MESSAGE);
          }else{
            JOptionPane.showMessageDialog(null, "!Printing", "Printer", JOptionPane.ERROR_MESSAGE);  
          }
      }catch(PrinterException e){
          
      }
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MABE3AT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MABE3AT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MABE3AT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MABE3AT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MABE3AT_view().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField c_price;
    private javax.swing.JTextField consnum;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JComboBox<String> jname;
    private javax.swing.JTextField ob_amount;
    private javax.swing.JTextField to_price;
    private javax.swing.JTextField u_price;
    private javax.swing.JComboBox<String> unit;
    private javax.swing.JTextField zbonname;
    // End of variables declaration//GEN-END:variables
}
