/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import classes.AutoCompletion;
import classes.moshtarayat_class;
import entities.MOSHTARAYAT;
import java.awt.event.KeyEvent;
import java.sql.Date;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Nowar
 */
public class moshtarayat extends javax.swing.JFrame {

    int bigbill = 0;
    Double sum=0.0;
    boolean state = false;
    DefaultTableModel tbd;

    /**
     * Creates new form moshtarayat
     */
    public moshtarayat() {
        initComponents();
        tbd = new DefaultTableModel();
        this.setLocationRelativeTo(null);
      
        

    }

    public static java.sql.Date convertFromJAVADateToSQLDate(
            java.util.Date javaDate) {
        java.sql.Date sqlDate = null;
        if (javaDate != null) {
            sqlDate = new Date(javaDate.getTime());
        }
        return sqlDate;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        object_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ob_amount = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        unit = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        u_price = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        to_price = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jo_price = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        c_price = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        old = new javax.swing.JComboBox<>();
        dz_price = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        dz_price_jomla = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        bill_num = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arabic Typesetting", 1, 48)); // NOI18N
        jLabel1.setText("إدخال فاتورة");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("اسم المادة :");

        object_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        object_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                object_nameActionPerformed(evt);
            }
        });
        object_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                object_nameKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("الكمية :");

        ob_amount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ob_amount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ob_amountKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ob_amountKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("الوحدة :");

        unit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        unit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "قطعة", "دزينة", "طقم" }));
        unit.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                unitItemStateChanged(evt);
            }
        });
        unit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unitActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("السعر الإفرادي :");

        u_price.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        u_price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                u_priceKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                u_priceKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("إجمالي السعر :");

        to_price.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        to_price.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        to_price.setEnabled(false);
        to_price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                to_priceKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("جملة قطعة :");

        jo_price.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jo_price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jo_priceKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("مستهلك قطعة :");

        c_price.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        c_price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                c_priceKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("التاريخ :");

        jDateChooser1.setDateFormatString("yyyy-MM-dd");
        jDateChooser1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("حفظ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2.setText("عودة");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        old.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        old.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));
        old.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                oldItemStateChanged(evt);
            }
        });

        dz_price.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dz_price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dz_priceKeyTyped(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("الدزينة :");

        dz_price_jomla.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dz_price_jomla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dz_price_jomlaKeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("الدزينة :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(u_price, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(to_price, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(dz_price, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(c_price, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(dz_price_jomla)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jo_price, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 16, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(12, 12, 12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(object_name, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel2))
                            .addComponent(old, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(ob_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(unit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(object_name, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(old, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(unit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ob_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(u_price, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(to_price, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jo_price, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dz_price_jomla, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(c_price, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dz_price, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setRowHeight(23);
        jScrollPane1.setViewportView(jTable1);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("رقم الفاتورة :");

        bill_num.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bill_num.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                bill_numKeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("المجموع :");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField1.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bill_num, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel11))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 756, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(490, 490, 490)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(bill_num, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int count = 0;
        int compare = 0;
        Object obj;
        String namex = "";
        boolean added;
        MOSHTARAYAT en = new MOSHTARAYAT();
        moshtarayat_class mo = new moshtarayat_class();
        String bill = bill_num.getText();
        if (!bill_num.getText().equals("")) {
            int billx = Integer.parseInt(bill);
            bigbill = billx;
            Date date = convertFromJAVADateToSQLDate(jDateChooser1.getDate());
            if ((!object_name.getText().equals("") || !old.getSelectedItem().toString().equalsIgnoreCase("-")) && !ob_amount.getText().equals("") && !u_price.getText().equals("") 
                    && !to_price.getText().equals("") && !jo_price.getText().equals("") && !c_price.getText().equals("")
                    ) {
              String name="";  
                if(state){
                    name=old.getSelectedItem().toString();
                }else{
                   name = object_name.getText();  
                }
                Double amount = Double.parseDouble(ob_amount.getText());
                String Sunit = unit.getSelectedItem().toString();
                int unit_price = Integer.parseInt(u_price.getText());
                Double total_price = Double.parseDouble(to_price.getText());
                sum=sum+total_price;
                int jomla_price = Integer.parseInt(jo_price.getText());
                int consumer_price = Integer.parseInt(c_price.getText());
                int dazena_price = Integer.parseInt(dz_price.getText());
                int daz_jomla=Integer.parseInt(dz_price_jomla.getText());
                en.setName(name);
                en.setAmount(amount);
                en.setUnit(Sunit);
                en.setUnit_price(unit_price);
                en.setTotal_price(total_price);
                en.setJomla_price(jomla_price);
                en.setJomla_daz(daz_jomla);
                en.setCons_price(consumer_price);
                en.setDz_price(dazena_price);
                en.setOb_date(date);
                try {
                    mo.addmoshtarayat(en);
                    int x = mo.maxnumber();
                    System.out.println("max is :" + x);
                    mo.addlink(billx, x);
                    object_name.setText("");
                    ob_amount.setText("");
                    u_price.setText("");
                    to_price.setText("");
                    jo_price.setText(String.valueOf(0));
                    c_price.setText(String.valueOf(0));
                    dz_price.setText(String.valueOf(0));
                    dz_price_jomla.setText(String.valueOf(0));
                    
                    if(!state)
                    old.addItem(name);

                    ((DefaultTableModel) jTable1.getModel()).setNumRows(0);
                    ArrayList<MOSHTARAYAT> ar = mo.showmosh(billx);
                    Object[] tablecolumnNames = new Object[7];
                    tablecolumnNames[0] = "التاريخ";
                    tablecolumnNames[1] = "الإجمالي";
                    tablecolumnNames[2] = "سعر الوحدة";
                    tablecolumnNames[3] = "الوحدة";
                    tablecolumnNames[4] = "الكمية";
                    tablecolumnNames[5] = "اسم القطعة";
                    tablecolumnNames[6] = "الرقم";

                    tbd.setColumnIdentifiers(tablecolumnNames);

                    this.jTable1.setModel(tbd);
                    Object[] RowItem = new Object[7];

                    for (int i = 0; i < ar.size(); i++) {

                        RowItem[0] = ar.get(i).getOb_date();
                        RowItem[1] = ar.get(i).getTotal_price();
                       
                        RowItem[2] = ar.get(i).getUnit_price();
                        RowItem[3] = ar.get(i).getUnit();
                        RowItem[4] = ar.get(i).getAmount();
                        RowItem[5] = ar.get(i).getName();
                        RowItem[6] = ar.get(i).getId();
                        tbd.addRow(RowItem);
                    }
                    TableColumn t= jTable1.getColumnModel().getColumn(5);
                    TableColumn t1= jTable1.getColumnModel().getColumn(6);
                    TableColumn t2= jTable1.getColumnModel().getColumn(4);
                    t.setPreferredWidth(250);
                    t1.setPreferredWidth(30);
                    t2.setPreferredWidth(55);
                    
                    jTextField1.setText(String.valueOf(sum));
                   
                } catch (SQLException ex) {
                    Logger.getLogger(moshtarayat.class.getName()).log(Level.SEVERE, null, ex);
                }

            } else {
                JOptionPane.showMessageDialog(null, "الرجاء ملئ جميع الحقول");
            }

        } else {
            JOptionPane.showMessageDialog(null, "الرجاء ملئ حقل رقم الفاتورة");

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        int count = 0;
        int compare = 0;
        Object obj;
        String name = "";
        boolean added;
        java.util.Date date = new java.util.Date();
        jDateChooser1.setDate(date);
        MOSHTARAYAT m = new MOSHTARAYAT();
        moshtarayat_class mc = new moshtarayat_class();
        ArrayList<String> ar = mc.getobjectsname();
        for (int j = 0; j < ar.size(); j++) {
            name = ar.get(j);
            count = old.getItemCount();
            added = false;
            for (int i = 1; i < count; i++) {
                obj = old.getItemAt(i);
                compare = name.compareToIgnoreCase(obj.toString());
                if (compare <= 0) {
                    old.insertItemAt(name, i);
                    added = true;
                    break;
                }
            }
            if (!added) {
                old.addItem(name);
            }
        }
        AutoCompletion.enable(old);
        jo_price.setText(String.valueOf(0));
        dz_price_jomla.setText(String.valueOf(0));
        c_price.setText(String.valueOf(0));
        dz_price.setText(String.valueOf(0));
        

    }//GEN-LAST:event_formWindowOpened

    private void u_priceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_u_priceKeyReleased
        try {
            Double x = Double.parseDouble(ob_amount.getText());
            if (!u_price.getText().equals("") && !ob_amount.getText().equals("")) {
                int y = Integer.parseInt(u_price.getText());
                Double z = x * y;
                to_price.setText(String.valueOf(z));
            } else {
                to_price.setText(String.valueOf(0));

            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_u_priceKeyReleased

    private void ob_amountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ob_amountKeyReleased
        try {
           Double x = Double.parseDouble(ob_amount.getText());
            if (!ob_amount.getText().equals("")) {
                int y = Integer.parseInt(u_price.getText());
                Double z = x * y;
                to_price.setText(String.valueOf(z));
            } else {
                to_price.setText(String.valueOf(0));
                ob_amount.setText(String.valueOf(0));
            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_ob_amountKeyReleased

    private void bill_numKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bill_numKeyTyped
        char vchar = evt.getKeyChar();
        if (!(Character.isDigit(vchar)) || (vchar == KeyEvent.VK_BACK_SPACE) || (vchar == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_bill_numKeyTyped

    private void ob_amountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ob_amountKeyTyped

    }//GEN-LAST:event_ob_amountKeyTyped

    private void u_priceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_u_priceKeyTyped
        char vchar = evt.getKeyChar();
        if (!(Character.isDigit(vchar)) || (vchar == KeyEvent.VK_BACK_SPACE) || (vchar == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_u_priceKeyTyped

    private void to_priceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_to_priceKeyTyped
        char vchar = evt.getKeyChar();
        if (!(Character.isDigit(vchar)) || (vchar == KeyEvent.VK_BACK_SPACE) || (vchar == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_to_priceKeyTyped

    private void jo_priceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jo_priceKeyTyped
        char vchar = evt.getKeyChar();
        if (!(Character.isDigit(vchar)) || (vchar == KeyEvent.VK_BACK_SPACE) || (vchar == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_jo_priceKeyTyped

    private void c_priceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_c_priceKeyTyped
        char vchar = evt.getKeyChar();
        if (!(Character.isDigit(vchar)) || (vchar == KeyEvent.VK_BACK_SPACE) || (vchar == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_c_priceKeyTyped

    private void oldItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_oldItemStateChanged
        state = true;
        object_name.setText("");
        String oldname = old.getSelectedItem().toString();
        String un = unit.getSelectedItem().toString();
      
        moshtarayat_class moc = new moshtarayat_class();
        ArrayList<Integer> ar = moc.getoldprices(oldname);
        int uprice=moc.getoldprice(oldname, un);
     
        u_price.setText(String.valueOf(uprice));
        jo_price.setText(String.valueOf(ar.get(1)));
        c_price.setText(String.valueOf(ar.get(2)));
        dz_price.setText(String.valueOf(ar.get(3)));
        dz_price_jomla.setText(String.valueOf(ar.get(4)));

    }//GEN-LAST:event_oldItemStateChanged

    private void object_nameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_object_nameKeyTyped
        state = false;
        old.setSelectedItem("-");
    }//GEN-LAST:event_object_nameKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       this.setVisible(false);
        First_view p=First_view.instance();
         p.pack();
        p.setLocationRelativeTo(null);
        p.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void dz_priceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dz_priceKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_dz_priceKeyTyped

    private void unitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unitActionPerformed

    private void unitItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_unitItemStateChanged
     String t=unit.getSelectedItem().toString();
     if(t.equalsIgnoreCase("طقم")){
         jLabel12.setText("طقم");
         jLabel13.setText("طقم");
     }
     else{
         jLabel12.setText("دزينة");
         jLabel13.setText("دزينة");
     }
        if(state){
           String oldname = old.getSelectedItem().toString();
        String un = unit.getSelectedItem().toString();
      
        moshtarayat_class moc = new moshtarayat_class();
       
        int uprice=moc.getoldprice(oldname, un);
     
        u_price.setText(String.valueOf(uprice));
       }
    }//GEN-LAST:event_unitItemStateChanged

    private void object_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_object_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_object_nameActionPerformed

    private void dz_price_jomlaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dz_price_jomlaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_dz_price_jomlaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(moshtarayat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(moshtarayat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(moshtarayat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(moshtarayat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new moshtarayat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bill_num;
    private javax.swing.JTextField c_price;
    private javax.swing.JTextField dz_price;
    private javax.swing.JTextField dz_price_jomla;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jo_price;
    private javax.swing.JTextField ob_amount;
    private javax.swing.JTextField object_name;
    private javax.swing.JComboBox<String> old;
    private javax.swing.JTextField to_price;
    private javax.swing.JTextField u_price;
    private javax.swing.JComboBox<String> unit;
    // End of variables declaration//GEN-END:variables
}
