/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import classes.update_class;
import entities.DAILY;
import entities.MABE3AT;
import entities.MOSHTARAYAT;
import java.sql.Date;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Nowar
 */
public class update extends javax.swing.JFrame {

    /**
     * Creates new form update
     */
    public update() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public static java.sql.Date convertFromJAVADateToSQLDate(
            java.util.Date javaDate) {
        java.sql.Date sqlDate = null;
        if (javaDate != null) {
            sqlDate = new Date(javaDate.getTime());
        }
        return sqlDate;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arabic Typesetting", 1, 48)); // NOI18N
        jLabel1.setText("كشف وتعديل");

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.setEnabled(false);
        jTable1.setRowHeight(25);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRadioButton1.setText("مشتريات");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRadioButton2.setText("مبيع جملة");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRadioButton3.setText("مبيع يومي");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("عرض");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("تعديل");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton3.setText("حفظ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton4.setText("عودة");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton5.setText("حذف");
        jButton5.setEnabled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jRadioButton2)
                                .addComponent(jRadioButton1))
                            .addComponent(jRadioButton3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 242, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 1263, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 967, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(500, 500, 500)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.setVisible(false);
        First_view p = First_view.instance();
        p.pack();
        p.setLocationRelativeTo(null);
        p.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        update_class up = new update_class();
        if (jRadioButton1.isSelected()) {
            Double sum = 0.0;
            ArrayList<MOSHTARAYAT> ar = up.showmoshtarayat();
            DefaultTableModel tbd = new DefaultTableModel();
            Object[] tablecolumnNames = new Object[11];
            tablecolumnNames[0] = "التاريخ";
            tablecolumnNames[1] = "سعر الدزينة للمستهلك";
            tablecolumnNames[2] = "سعر القطعة للمستهلك";
            tablecolumnNames[3] = "سعر الجملة للدزينة";
            tablecolumnNames[4] = "سعر الجملة للقطعة";
            tablecolumnNames[5] = "إجمالي السعر";
            tablecolumnNames[6] = "سعر الوحدة";
            tablecolumnNames[7] = "الوحدة";
            tablecolumnNames[8] = "الكمية";
            tablecolumnNames[9] = "اسم القطعة";
            tablecolumnNames[10] = "الرقم";

            tbd.setColumnIdentifiers(tablecolumnNames);

            this.jTable1.setModel(tbd);
            Object[] RowItem = new Object[11];

            for (int i = 0; i < ar.size(); i++) {

                RowItem[0] = ar.get(i).getOb_date();
                RowItem[1] = ar.get(i).getDz_price();
                RowItem[2] = ar.get(i).getCons_price();
                RowItem[3] = ar.get(i).getJomla_daz();
                RowItem[4] = ar.get(i).getJomla_price();
                sum = sum + ar.get(i).getTotal_price();
                RowItem[5] = ar.get(i).getTotal_price();
                RowItem[6] = ar.get(i).getUnit_price();
                RowItem[7] = ar.get(i).getUnit();
                RowItem[8] = ar.get(i).getAmount();
                RowItem[9] = ar.get(i).getName();
                RowItem[10] = ar.get(i).getId();
                tbd.addRow(RowItem);
            }
            TableColumn t = jTable1.getColumnModel().getColumn(9);
            TableColumn t3 = jTable1.getColumnModel().getColumn(7);
            TableColumn t1 = jTable1.getColumnModel().getColumn(0);
            TableColumn t2 = jTable1.getColumnModel().getColumn(10);
            t.setPreferredWidth(250);
            t2.setPreferredWidth(30);
            t1.setPreferredWidth(100);
            t3.setPreferredWidth(55);

        }
        if (jRadioButton2.isSelected()) {
            Double sum = 0.0;
            ArrayList<MABE3AT> ar = up.showmabe3at();
            DefaultTableModel tbd = new DefaultTableModel();
            Object[] tablecolumnNames = new Object[9];
            tablecolumnNames[0] = "التاريخ";
            tablecolumnNames[1] = "رقم الزبون";
            tablecolumnNames[2] = "سعر المستهلك";
            tablecolumnNames[3] = "إجمالي السعر";
            tablecolumnNames[4] = "سعر الوحدة";
            tablecolumnNames[5] = "الوحدة";
            tablecolumnNames[6] = "الكمية";
            tablecolumnNames[7] = "اسم القطعة";
            tablecolumnNames[8] = "الرقم";

            tbd.setColumnIdentifiers(tablecolumnNames);

            this.jTable1.setModel(tbd);
            Object[] RowItem = new Object[9];

            for (int i = 0; i < ar.size(); i++) {

                RowItem[0] = ar.get(i).getMa_date();
                RowItem[1] = ar.get(i).getConid();

                RowItem[2] = ar.get(i).getCons_price();
                sum = sum + ar.get(i).getTotalprice();
                RowItem[3] = ar.get(i).getTotalprice();
                RowItem[4] = ar.get(i).getPrice();
                RowItem[5] = ar.get(i).getUnit();
                RowItem[6] = ar.get(i).getAmount();
                RowItem[7] = ar.get(i).getName();
                RowItem[8] = ar.get(i).getId();
                tbd.addRow(RowItem);
            }
            TableColumn t = jTable1.getColumnModel().getColumn(7);
            TableColumn t1 = jTable1.getColumnModel().getColumn(0);
            TableColumn t2 = jTable1.getColumnModel().getColumn(8);
            t.setPreferredWidth(200);
            t2.setPreferredWidth(30);
            t1.setPreferredWidth(100);

        }
        if (jRadioButton3.isSelected()) {
            Double sum = 0.0;
            ArrayList<DAILY> ar = up.showdaily();
            DefaultTableModel tbd = new DefaultTableModel();
            Object[] tablecolumnNames = new Object[7];

            tablecolumnNames[0] = "التاريخ";
            tablecolumnNames[1] = "إجمالي السعر";
            tablecolumnNames[2] = "السعر";
            tablecolumnNames[3] = "الكمية";
            tablecolumnNames[4] = "الوحدة";
            tablecolumnNames[5] = "اسم القطعة";
            tablecolumnNames[6] = "الرقم";

            tbd.setColumnIdentifiers(tablecolumnNames);

            this.jTable1.setModel(tbd);
            Object[] RowItem = new Object[7];

            for (int i = 0; i < ar.size(); i++) {

                RowItem[0] = ar.get(i).getObdate();
                RowItem[1] = ar.get(i).getTotalprice();

                RowItem[2] = ar.get(i).getObprice();
                sum = sum + ar.get(i).getTotalprice();
                RowItem[3] = ar.get(i).getObamount();
                RowItem[4] = ar.get(i).getObunit();
                RowItem[5] = ar.get(i).getObname();
                RowItem[6] = ar.get(i).getId();

                tbd.addRow(RowItem);
            }
            TableColumn t = jTable1.getColumnModel().getColumn(5);
            TableColumn t1 = jTable1.getColumnModel().getColumn(0);
            TableColumn t2 = jTable1.getColumnModel().getColumn(6);
            t.setPreferredWidth(200);
            t2.setPreferredWidth(30);
            t1.setPreferredWidth(100);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTable1.setEnabled(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        update_class uc = new update_class();
        DAILY da = new DAILY();
        MABE3AT ma = new MABE3AT();
        MOSHTARAYAT mo = new MOSHTARAYAT();
        int row = jTable1.getSelectedRow();

        try {
            if (jRadioButton1.isSelected()) {

                int id = Integer.parseInt(jTable1.getModel().getValueAt(row, 10).toString());
                mo.setId(id);
                String name = jTable1.getModel().getValueAt(row, 9).toString();
                mo.setName(name);
                Double amount = Double.parseDouble(jTable1.getModel().getValueAt(row, 8).toString());
                mo.setAmount(amount);
                String unit = jTable1.getModel().getValueAt(row, 7).toString();
                mo.setUnit(unit);
                int unitprice = Integer.parseInt(jTable1.getModel().getValueAt(row, 6).toString());
                mo.setUnit_price(unitprice);
                Double totalprice = Double.parseDouble(jTable1.getModel().getValueAt(row, 5).toString());
                mo.setTotal_price(totalprice);
                int jomla = Integer.parseInt(jTable1.getModel().getValueAt(row, 4).toString());
                mo.setJomla_price(jomla);
                int dazjomla = Integer.parseInt(jTable1.getModel().getValueAt(row, 3).toString());
                mo.setJomla_daz(dazjomla);
                int cons = Integer.parseInt(jTable1.getModel().getValueAt(row, 2).toString());
                mo.setCons_price(cons);
                int consdaz = Integer.parseInt(jTable1.getModel().getValueAt(row, 1).toString());
                mo.setDz_price(consdaz);

                uc.updatemoshtarayat(mo);

            }
            if (jRadioButton2.isSelected()) {
                int id = Integer.parseInt(jTable1.getModel().getValueAt(row, 8).toString());
                ma.setId(id);
                String name = jTable1.getModel().getValueAt(row, 7).toString();
                ma.setName(name);
                Double amount = Double.parseDouble(jTable1.getModel().getValueAt(row, 6).toString());
                ma.setAmount(amount);
                String unit = jTable1.getModel().getValueAt(row, 5).toString();
                ma.setUnit(unit);
                int unitprice = Integer.parseInt(jTable1.getModel().getValueAt(row, 4).toString());
                ma.setPrice(unitprice);
                Double totalprice = Double.parseDouble(jTable1.getModel().getValueAt(row, 3).toString());
                ma.setTotalprice(totalprice);

                int cons = Integer.parseInt(jTable1.getModel().getValueAt(row, 2).toString());
                ma.setCons_price(cons);
                int coid = Integer.parseInt(jTable1.getModel().getValueAt(row, 1).toString());
                ma.setConid(cons);

                uc.updatemabe3at(ma);

            }
            if (jRadioButton3.isSelected()) {
                int id = Integer.parseInt(jTable1.getModel().getValueAt(row, 6).toString());
                da.setId(id);
                String name = jTable1.getModel().getValueAt(row, 5).toString();
                da.setObname(name);
                String unit = jTable1.getModel().getValueAt(row, 4).toString();
                da.setObunit(unit);
                Double amount = Double.parseDouble(jTable1.getModel().getValueAt(row, 3).toString());
                da.setObamount(amount);

                int unitprice = Integer.parseInt(jTable1.getModel().getValueAt(row, 2).toString());
                da.setObprice(unitprice);
                Double totalprice = Double.parseDouble(jTable1.getModel().getValueAt(row, 1).toString());
                da.setTotalprice(totalprice);
                System.out.println(String.valueOf(id));

                uc.updatedaily(da);
            }
        } catch (Exception e) {
            e.getMessage();
        }


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        update_class uc = new update_class();
        try{
        int row = jTable1.getSelectedRow();
       
        if (jRadioButton1.isSelected()) {

            int id = Integer.parseInt(jTable1.getModel().getValueAt(row, 10).toString());
             try {
                 uc.deletemoshtarayt(id);
                 uc.deletemoshlink(id);
                   Double sum = 0.0;
            ArrayList<MOSHTARAYAT> ar = uc.showmoshtarayat();
            DefaultTableModel tbd = new DefaultTableModel();
            Object[] tablecolumnNames = new Object[11];
            tablecolumnNames[0] = "التاريخ";
            tablecolumnNames[1] = "سعر الدزينة للمستهلك";
            tablecolumnNames[2] = "سعر القطعة للمستهلك";
            tablecolumnNames[3] = "سعر الجملة للدزينة";
            tablecolumnNames[4] = "سعر الجملة للقطعة";
            tablecolumnNames[5] = "إجمالي السعر";
            tablecolumnNames[6] = "سعر الوحدة";
            tablecolumnNames[7] = "الوحدة";
            tablecolumnNames[8] = "الكمية";
            tablecolumnNames[9] = "اسم القطعة";
            tablecolumnNames[10] = "الرقم";

            tbd.setColumnIdentifiers(tablecolumnNames);

            this.jTable1.setModel(tbd);
            Object[] RowItem = new Object[11];

            for (int i = 0; i < ar.size(); i++) {

                RowItem[0] = ar.get(i).getOb_date();
                RowItem[1] = ar.get(i).getDz_price();
                RowItem[2] = ar.get(i).getCons_price();
                RowItem[3] = ar.get(i).getJomla_daz();
                RowItem[4] = ar.get(i).getJomla_price();
                sum = sum + ar.get(i).getTotal_price();
                RowItem[5] = ar.get(i).getTotal_price();
                RowItem[6] = ar.get(i).getUnit_price();
                RowItem[7] = ar.get(i).getUnit();
                RowItem[8] = ar.get(i).getAmount();
                RowItem[9] = ar.get(i).getName();
                RowItem[10] = ar.get(i).getId();
                tbd.addRow(RowItem);
            }
             TableColumn t = jTable1.getColumnModel().getColumn(9);
            TableColumn t1 = jTable1.getColumnModel().getColumn(0);
            TableColumn t2 = jTable1.getColumnModel().getColumn(10);
            t.setPreferredWidth(200);
            t2.setPreferredWidth(30);
            t1.setPreferredWidth(100);
                 
             } catch (SQLException ex) {
                 Logger.getLogger(update.class.getName()).log(Level.SEVERE, null, ex);
             }
            
        }
        if (jRadioButton2.isSelected()) {
            int id = Integer.parseInt(jTable1.getModel().getValueAt(row, 8).toString());
             try {
                 uc.deletemabe3at(id);
                 uc.deletemabe3atzbon(id);
                 Double sum = 0.0;
            ArrayList<MABE3AT> ar = uc.showmabe3at();
            DefaultTableModel tbd = new DefaultTableModel();
            Object[] tablecolumnNames = new Object[9];
            tablecolumnNames[0] = "التاريخ";
            tablecolumnNames[1] = "رقم الزبون";
            tablecolumnNames[2] = "سعر المستهلك";
            tablecolumnNames[3] = "إجمالي السعر";
            tablecolumnNames[4] = "سعر الوحدة";
            tablecolumnNames[5] = "الوحدة";
            tablecolumnNames[6] = "الكمية";
            tablecolumnNames[7] = "اسم القطعة";
            tablecolumnNames[8] = "الرقم";

            tbd.setColumnIdentifiers(tablecolumnNames);

            this.jTable1.setModel(tbd);
            Object[] RowItem = new Object[9];

            for (int i = 0; i < ar.size(); i++) {

                RowItem[0] = ar.get(i).getMa_date();
                RowItem[1] = ar.get(i).getConid();

                RowItem[2] = ar.get(i).getCons_price();
                sum = sum + ar.get(i).getTotalprice();
                RowItem[3] = ar.get(i).getTotalprice();
                RowItem[4] = ar.get(i).getPrice();
                RowItem[5] = ar.get(i).getUnit();
                RowItem[6] = ar.get(i).getAmount();
                RowItem[7] = ar.get(i).getName();
                RowItem[8] = ar.get(i).getId();
                tbd.addRow(RowItem);
            }
            TableColumn t = jTable1.getColumnModel().getColumn(7);
            TableColumn t1 = jTable1.getColumnModel().getColumn(0);
            TableColumn t2 = jTable1.getColumnModel().getColumn(8);
            t.setPreferredWidth(200);
            t2.setPreferredWidth(30);
            t1.setPreferredWidth(100);
             } catch (SQLException ex) {
                 Logger.getLogger(update.class.getName()).log(Level.SEVERE, null, ex);
             }
            
        }
        if (jRadioButton3.isSelected()) {
            int id = Integer.parseInt(jTable1.getModel().getValueAt(row, 6).toString());
             try {
                 uc.deletedaily(id);
                   Double sum = 0.0;
            ArrayList<DAILY> ar = uc.showdaily();
            DefaultTableModel tbd = new DefaultTableModel();
            Object[] tablecolumnNames = new Object[7];

            tablecolumnNames[0] = "التاريخ";
            tablecolumnNames[1] = "إجمالي السعر";
            tablecolumnNames[2] = "السعر";
            tablecolumnNames[3] = "الكمية";
            tablecolumnNames[4] = "الوحدة";
            tablecolumnNames[5] = "اسم القطعة";
            tablecolumnNames[6] = "الرقم";

            tbd.setColumnIdentifiers(tablecolumnNames);

            this.jTable1.setModel(tbd);
            Object[] RowItem = new Object[7];

            for (int i = 0; i < ar.size(); i++) {

                RowItem[0] = ar.get(i).getObdate();
                RowItem[1] = ar.get(i).getTotalprice();

                RowItem[2] = ar.get(i).getObprice();
                sum = sum + ar.get(i).getTotalprice();
                RowItem[3] = ar.get(i).getObamount();
                RowItem[4] = ar.get(i).getObunit();
                RowItem[5] = ar.get(i).getObname();
                RowItem[6] = ar.get(i).getId();

                tbd.addRow(RowItem);
            }
            TableColumn t = jTable1.getColumnModel().getColumn(5);
            TableColumn t1 = jTable1.getColumnModel().getColumn(0);
            TableColumn t2 = jTable1.getColumnModel().getColumn(6);
            t.setPreferredWidth(200);
            t2.setPreferredWidth(30);
            t1.setPreferredWidth(100);
             } catch (SQLException ex) {
                 Logger.getLogger(update.class.getName()).log(Level.SEVERE, null, ex);
             }
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"الرجاء تحديد سطر أولا");
        }
        

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
      jButton5.setEnabled(true);

    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
